
.PHONY:	always

all:	tarlisted

CC=gcc

CFLAGS=	-O2 #-fstack-protector-all
LFLAGS=	-s

WARN0=	-Wall -Wstrict-prototypes -pedantic -Wno-long-long
WARN1=	$(WARN0) -Wcast-align -Wpointer-arith  # -Wfloat-equal #-Werror
WARN=	$(WARN1) -W -Wwrite-strings -Wcast-qual -Wshadow  # -Wconversion

LFOPT=	-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64

TLOBJS=	tarlisted.o

tarlisted: tarlisted.o
	$(CC) $(LFLAGS) -o $@ $(TLOBJS) $(LFOPT)

tarlisted.o: tarlisted.c Makefile
	$(CC) $(CFLAGS) $(WARN) -c -o $@ $< $(LFOPT)

test:	tarlisted
	sed -n 's/#[:]#//p' tarlisted.c | ./tarlisted -V -zo test.tar.gz

#FIXME more tests.

chkprefix: always
	@[ x"$(PREFIX)" != x ] \
		|| { sed -n 's/^#pfx: \?//p;' Makefile; false; }

#pfx:
#pfx:  Can not install: PREFIX missing.
#pfx:
#pfx:  try for example: make install PREFIX=/usr/local
#pfx:

install: tarlisted chkprefix
	sed -n "/^itl: / { s/itl://; s|%PREFIX|$$PREFIX|p; }" Makefile \
		| ./tarlisted '|' tar -C / -xvf -

itl: tarlisted file version 2
itl: 755 root root . %PREFIX /
itl: 755 root root . %PREFIX/bin /
itl: 755 root root . %PREFIX/bin/tarlisted tarlisted
itl: 755 root root . %PREFIX/man /
itl: 755 root root . %PREFIX/man/man1 /
itl: 644 root root . %PREFIX/man/man1/tarlisted.1 tarlisted.1
itl: tarlisted file end


GitLog32: always #SvnVersion_unmodified #always #$(FILES)
	git log --name-status a1cdf75e68cc > $@


txz32:	GitLog32
	@ct=`exec git --no-pager log -1 --pretty='%ct' a1cdf75e68cc`; \
	version=`sed -n 's/^#define VERSION "//; T; s/".*//p; q;' tarlisted.c`\
	; sed '1,/^$@.pl:/d;/^#.#eos/q' Makefile | perl - "$$version" $$ct

txz32.pl:
	use strict; use warnings; use tarlisted;
	my $version = shift;
	my $arcname = "tarlisted-$version";
	print "Creating '$arcname.tar.xz...\n";
	tarlisted_open "$arcname.tar.xz", 'xz';
	my $timestamp = shift;
	my @go = ( $timestamp, 0, 0, 'root', 'root' );
	&tarlisted_mkdir ($arcname, 0755, @go);
	foreach ( qw/tarlisted.c tarlisted.1 Makefile GitLog32/ ) {
		print "Adding '$_'\n";
		my $name = "$arcname/$_";
		tarlisted_cp $_, $name, undef, @go;
	}
	tarlisted_close;
#	#eos
	exit 1; # not reached
	__END__


# this is deprecated to the above usage, but will be kept for reference.
targz: tarlisted GitLog32
	sed '1,/^$@.sh:/d;/^#.#eos/q' Makefile | sh -s yes

targz.sh:
	test -n "$1" || exit 1 # internal shell script; not to be made directly
	set -eu
	for n in tarlisted.c tarlisted.1 Makefile GitLog32
	do
		echo 644 root root . tarlisted-$version/$n $n
	done | ./tarlisted -V -zo tarlisted-$version.tar.gz
	set +e
	echo Created tarlisted-$version.tar.gz
#	#eos
	exit 1 # not reached


tarlisted32.md:
	sed '1,/^$@.sh:/d;/^#.#eos/q' Makefile | sh -s "$@"
	@echo check date in tarlisted.1 separately

tarlisted32.md.sh:
	test -n "$1" || exit 1 # internal shell script; not to be made directly
	set -eu
	case ${BASH_VERSION-} in *.*) shopt -s xpg_echo; esac
	exec > "$2"
	GROFF_NO_SGR=1 TERM=vt100; export GROFF_NO_SGR TERM
	echo "<!-- Generated by make $1 embedding tarlisted.1 to the content -->"
	echo
	echo '<pre>'
	groff -man -T latin1 tarlisted.1 | perl -e '
	my %htmlqh = qw/& &amp;   < &lt;   > &gt;   '\'' &apos;   " &quot;/;
	sub htmlquote($) { $_[0] =~ s/([&<>'\''"])/$htmlqh{$1}/ge; }
	while (<>) { htmlquote $_; s/[_&]\010&/&/g;
		s/((?:_\010[^_])+)/<u>$1<\/u>/g; s/_\010(.)/$1/g;
		s/((?:.\010.)+)/<b>$1<\/b>/g; s/.\010(.)/$1/g; print $_; }'
	echo '</pre>'
	exec > /dev/null
#	#eos
	exit 1 # not reached

clean: always
	rm -f tarlisted *.o test.* GitLog32 *~

distclean: clean

.SUFFIXES:
