.\" Hey, EMACS: -*- nroff -*-
.\"	Copyright (c) 2006 Tomi Ollila
.\"	    All rights reserved
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\"   1. Redistributions of source code must retain the above copyright
.\"      notice, this list of conditions and the following disclaimer.
.\"   2. Redistributions in binary form must reproduce the above copyright
.\"      notice, this list of conditions and the following disclaimer in
.\"      the documentation and/or other materials provided with the
.\"      distribution.
.\"   4. The names of the authors may not be used to endorse or promote
.\"      products derived from this software without specific prior
.\"      written permission.

.TH tarlisted 1 "Mar 12, 2009"

.SH NAME
tarlisted \- Create tar archive based on description list contents

.SH SYNOPSIS
.B tarlisted 
.I [-nVhzj] [-i infile] [(-o|-a) outfile] [| ppcmd [args]]
.br

.SH DESCRIPTION

\fBTarlisted\fP takes lines of text as an input and creates tar archive
based on that information.  

Each line contains permission, user, group and pathname that are to
be written in header part of the tar entry. In addition to that, at
the end of line the syntax varies depending the file type archived.
For example in case of reqular files the filename where file content
is read is added. Tarlisted creates POSIX.1-1998 tar file format 
(only) and can archive all the (seven) file types it supports.

.SH OPTIONS
.TP
.B -\fIn\fP
Just check tarlist contents, not doing anything else.
.TP
.B -\fIV\fP
Verbose output.
.TP
.B -\fIi\fP
Defines input file, instead of stdin.
.TP
.B -\fIo\fP
Defines output file, instead of stdout. Required if '|' not used.
Giving - will use stdout anyway (if there is need for it).
.TP
.B -\fIa\fP
Appends to output file. No compression nor postprosessing appicable.
.TP
.B -\fIz\fP
Compresses archive with gzip. Mutually exclusive with -j and '|'.
.TP
.B -\fIj\fP
Compresses archive with gzip. Mutually exclusive with -z and '|'.
.TP
.B -\fIM\fP
Creates md5 checksum output instead of tar.
.TP
.B -\fIO\fP
Comma-separated list of keywords for 'only' lines. See below.
.TP
.B -\fIh\fP
help
.TP
.B \fI| ppcmd [args]\fP
Internal piping to postprocess command. Archive output will be sent 
to this program for further use. Also, if postprocess
command returns nonzero value, tarlisted will exit with value 1.

.SH SYNTAX

Files and directories to be archived are read from input file,
each line in one of the formats:

    <perm> <uname> <gname> . <tarfilename> <sysfilename>
    <perm> <uname> <gname> . <tarfilename> /
     ---   <uname> <gname> . <tarfilename> -> <symlink>
     ===   <uname> <gname> . <tarfilename> => <hardlink>
    <perm> <uname> <gname> . <tarfilename> // c <devmajor> <devminor>
    <perm> <uname> <gname> . <tarfilename> // b <devmajor> <devminor>
    <perm> <uname> <gname> . <tarfilename> // fifo

  Where:
     perm:         file permission in octal number format.
     uname:        name of the user this file is owned.
     gname:        name of the group this file belongs.
     .:            future extension for time...
     tarfilename:  name of the file that is written to the tar archive.

     sysfilename:  file to be added from filesystem.
     /:            add directory to the tar archive.
     ->:           add tarfilename as symbolic link to given name.
     =>:           add tarfilename as hard link to given name.
     // c ...:     add character device to the tar archive.
     // b ...:     add block device to the tar archive.
     // fifo:      add fifo (named pipe) file to the tar archive.

Backspace "\\" must be used when adding [back]spaces to filenames.

Input file may also have lines

    tarlisted file format 3
    tarlisted file end

The first one can be used to request strict format check. The second
is added for symmetry.

And also:

    only <keyword1>[ <keyword2>[ <keyword3>]]
    all

These are used for conditional selection of input. If none of the
-O command line strings match for any of the keywords after \fIonly\fP
above, the following lines will be excluded, until there is matching
\fIonly\fP-line, or \fIall\fP-line. \fIAll\fP resets to include all
following lines.

Output format is POSIX Unix Standard TAR (ustar, IEEE Std 1003.1-1988)

.SH EXIT VALUE

tarlisted exits with 0 if everything goes ok. On failure it might exit
with nonzero value.

.SH EXAMPLES

First, just one that shows all supported file types.

  $ ./tarlisted -o test.tar << EOF
  tarlisted file format 2
   755 root root   . /usr/bin/tarlisted ./tarlisted
   700 too  too    . /tmp/path/to/nowhr /
   --- unski unski . /one\\ symlink -> /where/ever
   === wheel wheel . /one\\ hrdlink => /bin/echo
   666 root  root  . /dev/zero  // c 1 5
   640 root  disk  . /dev/loop0 // b 7 0
   600 root  root  . /dev/initctl // fifo
  tarlisted file end
  EOF

The above created test.tar with content: 

  $ tar tvf test.tar
  -rwxr-xr-x root/root  12453 2006-04-25 00:41:48 usr/bin/tarlisted
  drwx------ too/too        0 2006-04-25 00:42:53 tmp/path/to/nowhr
  lrwxrwxrwx unski/unski    0 2006-04-25 00:42:53 one symlink -> /where/ever
  hrwxrwxrwx wheel/wheel    0 2006-04-25 00:42:53 one hrdlink link to /bin/echo
  crw-rw-rw- root/root    1,5 2006-04-25 00:42:53 dev/zero
  brw-r----- root/disk    7,0 2006-04-25 00:42:53 dev/loop0
  prw------- root/root      0 2006-04-25 00:42:53 dev/initctl

If -M were given on above command line, the output would look like:

  $ cat test.tar
  b4118203da5d3829c62e468b67972615  usr/bin/tarlisted

I.e. the only file in tarlist was md5summed for output.
(I suggest changing ending to something like .md5sum instead)

Another to install perl4 (compiled from 4.0.36) (using installed tarlisted).

  $ PREFIX=/usr
  $ tarlisted '|' tar -C $PREFIX -xvf - << EOF 
   755 root root . bin/perl4 src/perl
   644 root root . man/man1/perl4.1 src/perl.man
  EOF

  or, the above with same result:

  $ PREFIX=/usr
  $ tarlisted '|' tar -C / -xvf - << EOF 
   755 root root . $PREFIX/bin/perl4 src/perl
   644 root root . $PREFIX/man/man1/perl4.1 src/perl.man
  EOF

Finally, compress on the fly with bzip2

  $ echo 755 root root . /usr/bin/tarlisted tarlisted \\
    | ./tarlisted -o tl.tar.bz2 '|' bzip -c

Same with tarlisted 2.2 (or newer)

  $ echo 755 root root . /usr/bin/tarlisted tarlisted \\
    | ./tarlisted -jo tl.tar.bz2

.SH CAVEAT

Remember to escape | from shell when using the internal pipeline
feature of tarlisted. There are three ways to enter that on the
command line: '|', "|" and \\|. Now there is less chance for that
since -o is seldom used in this case -- tarlisted will not work
without -o now if '|' is not used.

.SH TODO

Add features from latest POSIX tar specifications to 
support long filenames when necessary. \" option -x to enable

Plan and implement "modification time" setting.

.SH AUTHOR
written by Tomi Ollila

.SH COPYRIGHT

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions
 are met:
 
 1. Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.
 2. Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in
    the documentation and/or other materials provided with the
    distribution.
 4. The names of the authors may not be used to endorse or promote
    products derived from this software without specific prior
    written permission.
 
 THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
   

.SH SEE ALSO
.PD 0
\fBtar\fP(1),
\fBstar\fP(1),
\fBtar\fP(5)
